spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: devTimeTracker-rest-api
            client-secret: t0JJg0MQxvyiZoErK6Gy8hmdpcQgjYFC
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, profile, email
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/devTimeTracker
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/devtimetracker}
    username: ${SPRING_DATASOURCE_USERNAME:devuser}
    password: ${SPRING_DATASOURCE_PASSWORD:devpassword}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081

jwt:
  auth:
    converter:
      resource-id: devTimeTracker-rest-api
      principle-attribute: preferred_username

keycloak:
  client-id: devTimeTracker-rest-api
  client-secret: t0JJg0MQxvyiZoErK6Gy8hmdpcQgjYFC
  redirect-uri: http://localhost:8081/api/auth/callback
  token-uri: http://localhost:8080/realms/devTimeTracker/protocol/openid-connect/token
  realm: devTimeTracker
  auth-uri: http://localhost:8080/realms/devTimeTracker/protocol/openid-connect/auth
  logout-uri: http://localhost:8080/realms/devTimeTracker/protocol/openid-connect/logout
